export const ErrorCodeEnum = {
  AUTH_EMAIL_ALREADY_EXISTS: "AUTH_EMAIL_ALREADY_EXISTS",
  AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  AUTH_INVALID_TOKEN: "AUTH_INVALID_TOKEN",
  AUTH_TOKEN_EXPIRED: "AUTH_TOKEN_EXPIRED",
  AUTH_TOKEN_NOT_FOUND: "AUTH_TOKEN_NOT_FOUND",
  AUTH_TOKEN_NOT_PROVIDED: "AUTH_TOKEN_NOT_PROVIDED",
  AUTH_TOKEN_NOT_VALID: "AUTH_TOKEN_NOT_VALID",
  BAD_REQUEST: "BAD_REQUEST",

  // ACCESS_DENIED
  ACCESS_UNAUTHORIZED: "ACCESS_UNAUTHORIZED",
  ACCESS_FORBIDDEN: "ACCESS_FORBIDDEN",

  // VALIDATION_ERROR
  VALIDATION_ERROR: "VALIDATION_ERROR",

  // NOT_FOUND
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",

  // INTERNAL_SERVER_ERROR
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
} as const;

export type ErrorCodeEnumType =
  (typeof ErrorCodeEnum)[keyof typeof ErrorCodeEnum];
